# Makefile for cache_info kernel module
obj-m += cache_info.o

# Build from kernel source tree:
#   make -C /path/to/kernel-source M=$(pwd) modules
#
# Or if this directory is under the kernel source:
#   make M=kmodules/cache_info modules
